$().ready(function(){
    $("#home").click(function(){
        $("#ho").removeClass("hidden");
        $("#braz").addClass("hidden");
        $("#as").addClass("hidden");
        $("#mx").addClass("hidden");
        $("#mea").addClass("hidden");
        $("#cov").addClass("hidden");
    });
    $("#br").click(function(){
        $("#braz").removeClass("hidden");
        $("#ho").addClass("hidden");
        $("#as").addClass("hidden");
        $("#mx").addClass("hidden");
        $("#mea").addClass("hidden");
        $("#cov").addClass("hidden");
    });
    $("#aus").click(function(){
        $("#as").removeClass("hidden");
        $("#ho").addClass("hidden");
        $("#braz").addClass("hidden");
        $("#mx").addClass("hidden");
        $("#mea").addClass("hidden");
        $("#cov").addClass("hidden");
    });
    $("#mex").click(function(){
        $("#mx").removeClass("hidden");
        $("#ho").addClass("hidden");
        $("#braz").addClass("hidden");
        $("#as").addClass("hidden");
        $("#mea").addClass("hidden");
        $("#cov").addClass("hidden");
    });
    $("#me").click(function(){
        $("#mea").removeClass("hidden");
        $("#ho").addClass("hidden");
        $("#braz").addClass("hidden");
        $("#as").addClass("hidden");
        $("#mx").addClass("hidden");
        $("#cov").addClass("hidden");
    });
    $("#co").click(function(){
        $("#cov").removeClass("hidden");
        $("#ho").addClass("hidden");
        $("#braz").addClass("hidden");
        $("#as").addClass("hidden");
        $("#mx").addClass("hidden");
        $("#mea").addClass("hidden");
    });
});